{% set name = "rxn_rebuild" %}
{% set version = "3.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.zip
  sha256: db71b940e6879ac07eb3cc594cc121511adf3d41c96d4e6b41f111ec632a820e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }}  setup.py install

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - brs_utils >=1.6.0
    - rr_cache >=3.3.2
    - chemlite

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - python -m {{ name|lower }} --help
    - cd tests
    - pytest -v
about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: Rebuild full reaction from reaction rule
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
    - ramez17khaled
