{% set name = "rxn_rebuild" %}
{% set version = "3.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.zip
  sha256: 57c788c78c98177c7938f92b4d24bc366a9f33eb84ade1735838f317345652f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - brs_utils
    - rr_cache >=3.3.2
    - chemlite

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - python -m {{ name|lower }} --help
    - cd tests
    - pytest -v
about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: Rebuild full reaction from reaction rule
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
